### ISSUE TITLE
Move under the WordPress GitHub organization

### ISSUE THREAD

**Issue by adamziel** [WordPress/action-wp-playground-pr-preview#13]
It would be great to offer an official WordPress reusable GitHub action. Would you be open to moving this repo under the WordPress org? This would unlock recommending it in all Playground docs and materials.

**Comment by juanfra** [comment]
It looks like this one can be closed.

**Comment by adamziel** [comment]
CC @bph, it would be lovely to share this repo more broadly. Also cc @akirk on https://github.com/akirk/awesome-wordpress-playground
